enable-module-update = true
parallel-jobs = 1
patches-version = "latest"
cli-version = "latest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/elohim-etz/morphe-builder/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe
[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
integrations-source = "MorpheApp/revanced-integrations"
rv-brand = "MorpheApp ReVanced"
excluded-patches = "'Custom branding'"
arch = "arm64-v8a"
build-mode = "both"

[Youtube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
integrations-source = "MorpheApp/revanced-integrations"
rv-brand = "MorpheApp ReVanced"
excluded-patches = "'Custom branding' 'Change header' 'Custom player overlay opacity'"
arch = "arm64-v8a"
build-mode = "both"
